---
version: "3.8"

# Quick start configuration with pre-built images
# Run with: docker-compose -f docker-compose.quickstart.yml up -d

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: alabuga_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - main

  # Redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - main

  # Django Backend (pre-built image)
  backend:
    image: ghcr.io/abat-voix/alabuga-oneplusplus-backend:latest
    restart: unless-stopped
    volumes:
      - django_static:/app/alabuga/static
      - django_media:/app/alabuga/media
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: your-secret-key-for-demo
      DEBUG: "True"
      DJANGO_DATABASE_HOST: postgres
      DJANGO_DATABASE_PORT: 5432
      POSTGRES_DB: alabuga_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_DATABASE_USER: postgres
      DJANGO_DATABASE_PASSWORD: postgres
      POSTGRES_NAME: alabuga_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin
      DOMAIN_NAME: localhost
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: /usr/local/bin/start-web-server
    networks:
      - main

  # Celery Worker
  celery-worker:
    image: ghcr.io/abat-voix/alabuga-oneplusplus-backend:latest
    restart: unless-stopped
    environment:
      DJANGO_DATABASE_HOST: postgres
      DJANGO_DATABASE_PORT: 5432
      POSTGRES_DB: alabuga_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_DATABASE_USER: postgres
      DJANGO_DATABASE_PASSWORD: postgres
      POSTGRES_NAME: alabuga_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: poetry run celery -A alabuga.celery worker --pool=threads --loglevel=info
    networks:
      - main

  # Celery Beat
  celery-beat:
    image: ghcr.io/abat-voix/alabuga-oneplusplus-backend:latest
    restart: unless-stopped
    environment:
      DJANGO_DATABASE_HOST: postgres
      DJANGO_DATABASE_PORT: 5432
      POSTGRES_DB: alabuga_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_DATABASE_USER: postgres
      DJANGO_DATABASE_PASSWORD: postgres
      POSTGRES_NAME: alabuga_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: poetry run celery -A alabuga.celery beat --loglevel=info
    networks:
      - main

  # Flower (Celery monitoring)
  flower:
    image: ghcr.io/abat-voix/alabuga-oneplusplus-backend:latest
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      DJANGO_DATABASE_HOST: postgres
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
    command: poetry run celery -A alabuga.celery flower --port=5555
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  pgdata:
  redis_data:
  django_static:
  django_media: