# Quick start configuration with pre-built images
# Run with: docker compose -f docker-compose.quickstart.yml up -d
# Frontend: http://localhost
# Backend API: http://localhost/api
# Admin: http://localhost/admin
# Flower: http://localhost:5555

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.quickstart.conf:/etc/nginx/nginx.conf:ro
      - django_static:/var/www/django/static:ro
      - django_media:/var/www/django/media:ro
    depends_on:
      - backend
      - frontend
    networks:
      - main

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: alabuga_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - main

  # Redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - main

  # Django Backend
  backend:
    image: ghcr.io/bigbread57/alabuga-oneplusplus-backend:latest
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - django_static:/app/alabuga/static
      - django_media:/app/alabuga/media
    expose:
      - "8000"
    environment:
      DJANGO_SECRET_KEY: secret-key-for-demo
      DEBUG: "True"
      DJANGO_DATABASE_HOST: postgres
      DJANGO_DATABASE_PORT: 5432
      POSTGRES_DB: alabuga_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_DATABASE_USER: postgres
      DJANGO_DATABASE_PASSWORD: postgres
      POSTGRES_NAME: alabuga_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin
      DOMAIN_NAME: localhost
    depends_on:
      - postgres
      - redis
    command: /usr/local/bin/start-web-server
    networks:
      - main

  # Next.js Frontend
  frontend:
    image: ghcr.io/bigbread57/alabuga-oneplusplus-frontend:latest
    platform: linux/amd64
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_API_BASE_URL: http://localhost/api/v1
      API_URL: http://backend:8000/api/v1
    depends_on:
      - backend
    networks:
      - main

  # Celery Worker
  celery-worker:
    image: ghcr.io/bigbread57/alabuga-oneplusplus-backend:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      DJANGO_DATABASE_HOST: postgres
      DJANGO_DATABASE_PORT: 5432
      POSTGRES_DB: alabuga_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_DATABASE_USER: postgres
      DJANGO_DATABASE_PASSWORD: postgres
      POSTGRES_NAME: alabuga_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command: poetry run celery -A alabuga.celery worker --pool=threads --loglevel=info
    networks:
      - main

  # Celery Beat
  celery-beat:
    image: ghcr.io/bigbread57/alabuga-oneplusplus-backend:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      DJANGO_DATABASE_HOST: postgres
      DJANGO_DATABASE_PORT: 5432
      POSTGRES_DB: alabuga_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_DATABASE_USER: postgres
      DJANGO_DATABASE_PASSWORD: postgres
      POSTGRES_NAME: alabuga_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command: poetry run celery -A alabuga.celery beat --loglevel=info
    networks:
      - main

  # Flower (Celery monitoring)
  flower:
    image: ghcr.io/bigbread57/alabuga-oneplusplus-backend:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      DJANGO_DATABASE_HOST: postgres
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
    command: poetry run celery -A alabuga.celery flower --port=5555
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  pgdata:
  redis_data:
  django_static:
  django_media: