# Generated by Django 5.2.6 on 2025-10-02 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Multimedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("uuid", models.UUIDField(default=uuid.uuid4, help_text="UUID", unique=True, verbose_name="UUID")),
                ("multimedia", models.FileField(upload_to="multimedia", verbose_name="Файл")),
                ("object_id", models.PositiveIntegerField(verbose_name="Id объекта")),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
