# Generated by Django 5.2.6 on 2025-09-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0001_initial"),
        ("user", "0003_remove_user_role_character_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multimedia",
            name="creator",
        ),
        migrations.AddField(
            model_name="multimedia",
            name="character",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multimedias",
                to="user.character",
                verbose_name="Персонаж",
            ),
            preserve_default=False,
        ),
    ]
