# Generated by Django 5.2.6 on 2025-09-27 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0002_remove_multimedia_creator_multimedia_character"),
        ("user", "0003_remove_user_role_character_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multimedia",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multimedia",
                to="user.character",
                verbose_name="Персонаж",
            ),
        ),
    ]
