# Generated by Django 5.2.6 on 2025-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0003_alter_multimedia_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multimedia",
            name="multimedia",
            field=models.FileField(upload_to="multimedia", verbose_name="Файл"),
        ),
    ]
