# Generated by Django 5.2.6 on 2025-10-02 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("uuid", models.UUIDField(default=uuid.uuid4, help_text="UUID", unique=True, verbose_name="UUID")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "is_read",
                    models.BooleanField(default=False, help_text="Прочитано или нет", verbose_name="Прочитано или нет"),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Id объекта")),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("uuid", models.UUIDField(default=uuid.uuid4, help_text="UUID", unique=True, verbose_name="UUID")),
                ("text", models.TextField(verbose_name="Текст")),
                ("object_id", models.PositiveIntegerField(verbose_name="Id объекта")),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("uuid", models.UUIDField(default=uuid.uuid4, help_text="UUID", unique=True, verbose_name="UUID")),
                ("image", models.ImageField(blank=True, null=True, upload_to="posts", verbose_name="Изображение")),
                ("name", models.TextField(verbose_name="Название")),
                ("text", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("uuid", models.UUIDField(default=uuid.uuid4, help_text="UUID", unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="topics", verbose_name="Иконка")),
                ("color", models.CharField(blank=True, max_length=256, verbose_name="Цвет")),
            ],
            options={
                "verbose_name": "Тема",
                "verbose_name_plural": "Темы",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
