# Generated by Django 5.2.6 on 2025-09-27 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communication", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("game_world", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="user.character",
                verbose_name="Персонаж",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Тип содержимого",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="user.character",
                verbose_name="Персонаж",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Тип содержимого",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="user.character",
                verbose_name="Персонаж",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="communication.post",
                verbose_name="Родительский пост",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="game_worlds",
            field=models.ManyToManyField(
                blank=True,
                related_name="topics",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="communication.topic",
                verbose_name="Тема",
            ),
        ),
    ]
