# Generated by Django 5.2.6 on 2025-09-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("user", "0002_remove_character_experience_remove_character_rank_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("text", models.TextField(verbose_name="Текст")),
                ("object_id", models.PositiveIntegerField(verbose_name="Id объекта")),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="user.character",
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип содержимого",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
