# Generated by Django 5.2.6 on 2025-09-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_activitylog"),
        ("game_world", "0005_activitycategory_repeatability_and_more"),
        ("user", "0002_remove_character_experience_remove_character_rank_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="shot_description",
        ),
        migrations.AddField(
            model_name="comment",
            name="character",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="user.character",
                verbose_name="Персонаж",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="character",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="user.character",
                verbose_name="Персонаж",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.TextField(default=1, verbose_name="Название"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="color",
            field=models.CharField(blank=True, max_length=256, verbose_name="Цвет"),
        ),
        migrations.AddField(
            model_name="topic",
            name="game_worlds",
            field=models.ManyToManyField(
                blank=True, related_name="topics", to="game_world.gameworld", verbose_name="Игровой мир"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="topics", verbose_name="Иконка"),
        ),
        migrations.AlterField(
            model_name="post",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="communication.post",
                verbose_name="Родительский пост",
            ),
        ),
    ]
