# Generated by Django 5.2.6 on 2025-09-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="parent",
        ),
    ]
