# Generated by Django 5.2.6 on 2025-09-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0003_remove_post_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="is_read",
            field=models.BooleanField(
                default=False,
                help_text="Прочитано или нет",
                verbose_name="Прочитано или нет",
            ),
        ),
    ]
