# Generated by Django 4.2.24 on 2025-09-19 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game_mechanics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменен")),
                ("name", models.CharField(max_length=256, verbose_name="Название миссии")),
                ("description", models.TextField(verbose_name="Описание миссии")),
                ("experience_reward", models.IntegerField(default=0, verbose_name="Награда в опыте")),
                ("mana_reward", models.IntegerField(default=0, verbose_name="Награда в валюте")),
                ("order", models.IntegerField(default=0, verbose_name="Порядок в ветке")),
                (
                    "is_key_mission",
                    models.BooleanField(
                        default=False,
                        help_text="Обязательная миссия для получения ранга",
                        verbose_name="Ключевая миссия",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
            ],
            options={
                "verbose_name": "Миссия",
                "verbose_name_plural": "Миссии",
                "ordering": ["branch", "order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MissionBranch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменен")),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("QUEST", "Квест"),
                            ("RECRUITING", "Рекрутинг"),
                            ("LECTURING", "Лекторий"),
                            ("SIMULATOR", "Симулятор"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("icon", models.ImageField(blank=True, null=True, upload_to="mission_branches", verbose_name="Иконка")),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Ветка миссий",
                "verbose_name_plural": "Ветки миссий",
                "ordering": ["category", "order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MissionArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменен")),
                (
                    "drop_chance",
                    models.FloatField(
                        default=1.0,
                        help_text="Вероятность получения артефакта (0.0 - 1.0)",
                        verbose_name="Шанс выпадения",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_mechanics.artifact",
                        verbose_name="Артефакт",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="missions.mission", verbose_name="Миссия"
                    ),
                ),
            ],
            options={
                "verbose_name": "Артефакт миссии",
                "verbose_name_plural": "Артефакты миссий",
                "ordering": ["-id"],
                "abstract": False,
                "unique_together": {("mission", "artifact")},
            },
        ),
        migrations.AddField(
            model_name="mission",
            name="artifacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="missions",
                through="missions.MissionArtifact",
                to="game_mechanics.artifact",
                verbose_name="Награды-артефакты",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="missions.missionbranch",
                verbose_name="Ветка",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="min_rank",
            field=models.ForeignKey(
                blank=True,
                help_text="Минимальный ранг для доступа к миссии",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="available_missions",
                to="game_mechanics.rank",
                verbose_name="Минимальный ранг",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="required_missions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Миссии, которые нужно выполнить для доступа к этой миссии",
                related_name="unlocks_missions",
                to="missions.mission",
                verbose_name="Необходимые миссии",
            ),
        ),
        migrations.CreateModel(
            name="UserMission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменен")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Доступна"),
                            ("IN_PROGRESS", "В процессе"),
                            ("COMPLETED", "Выполнена"),
                            ("PENDING_REVIEW", "На проверке"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Начата")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершена")),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="Результат выполнения миссии (ссылки, файлы и т.д.)",
                        verbose_name="Результат",
                    ),
                ),
                ("review_comment", models.TextField(blank=True, verbose_name="Комментарий проверяющего")),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="missions.mission",
                        verbose_name="Миссия",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_missions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверил",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Миссия пользователя",
                "verbose_name_plural": "Миссии пользователей",
                "ordering": ["-id"],
                "abstract": False,
                "unique_together": {("user", "mission")},
            },
        ),
        migrations.CreateModel(
            name="RankMission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменен")),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_for_ranks",
                        to="missions.mission",
                        verbose_name="Миссия",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_missions",
                        to="game_mechanics.rank",
                        verbose_name="Ранг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обязательная миссия для ранга",
                "verbose_name_plural": "Обязательные миссии для рангов",
                "ordering": ["-id"],
                "abstract": False,
                "unique_together": {("rank", "mission")},
            },
        ),
        migrations.CreateModel(
            name="MissionCompetency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменен")),
                (
                    "experience",
                    models.IntegerField(
                        default=1, help_text="На сколько повысится уровень компетенции", verbose_name="Очки прокачки"
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="game_mechanics.competency",
                        verbose_name="Компетенция",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencies",
                        to="missions.mission",
                        verbose_name="Миссия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компетенция миссии",
                "verbose_name_plural": "Компетенции миссий",
                "ordering": ["-id"],
                "abstract": False,
                "unique_together": {("mission", "competency")},
            },
        ),
    ]
