# Generated by Django 5.2.6 on 2025-09-23 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_mechanics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("name", models.CharField(max_length=256, verbose_name="Название категории")),
                ("description", models.TextField(verbose_name="Описание категории")),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="mission_categories", verbose_name="Иконка"),
                ),
                ("color", models.CharField(max_length=256, verbose_name="Цвет")),
            ],
            options={
                "verbose_name": "Категория миссии",
                "verbose_name_plural": "Категории миссий",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("name", models.CharField(max_length=256, unique=True, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="competencies", verbose_name="Иконка")),
                (
                    "modifier",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Стандартный"),
                            ("EXPERIENCE_GAIN", "Прирост опыта"),
                            ("MANA_GAIN", "Прирост опыта"),
                            ("STORE_DISCOUNT", "Прирост опыта"),
                        ],
                        default="DEFAULT",
                        max_length=20,
                        verbose_name="Модификатор",
                    ),
                ),
                (
                    "modifier_value",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Значение модификатора в %",
                    ),
                ),
            ],
            options={
                "verbose_name": "Артефакт",
                "verbose_name_plural": "Артефакты",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GameWorld",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("color", models.CharField(max_length=256, verbose_name="Цвет")),
                (
                    "standard_experience",
                    models.PositiveIntegerField(
                        verbose_name="Стандартный размер опыта, начисляемый за очень простую миссию"
                    ),
                ),
                (
                    "standard_currency",
                    models.PositiveIntegerField(
                        verbose_name="Стандартный размер валюты, начисляемый за очень простую миссию"
                    ),
                ),
                ("currency_name", models.CharField(verbose_name="Название валюты")),
            ],
            options={
                "verbose_name": "Игровой мир",
                "verbose_name_plural": "Игровые миры",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MissionCompetency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                (
                    "experience",
                    models.IntegerField(
                        default=1, help_text="На сколько повысится уровень компетенции", verbose_name="Очки прокачки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Компетенция миссии",
                "verbose_name_plural": "Компетенции миссий",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MissionLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="mission_levels", verbose_name="Иконка")),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "multiplier_experience",
                    models.PositiveIntegerField(verbose_name="Множитель опыта от стандартного, в %"),
                ),
                (
                    "multiplier_currency",
                    models.PositiveIntegerField(verbose_name="Множитель опыта от стандартного, в %"),
                ),
                ("color", models.CharField(blank=True, max_length=256, verbose_name="Цвет")),
            ],
            options={
                "verbose_name": "Уровень миссии",
                "verbose_name_plural": "Уровни миссий",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="events", verbose_name="Иконка")),
                ("name", models.CharField(max_length=256, verbose_name="Название события")),
                ("description", models.TextField(verbose_name="Описание события")),
                ("experience", models.PositiveIntegerField(default=0, verbose_name="Награда в опыте")),
                ("currency", models.PositiveIntegerField(default=0, verbose_name="Награда в валюте")),
                (
                    "required_number",
                    models.PositiveIntegerField(verbose_name="Обязательное количество выполненных миссий"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                (
                    "start_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата и время для запуска"),
                ),
                ("time_to_complete", models.PositiveIntegerField(verbose_name="Время на выполнение в днях")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="game_world.activitycategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="game_mechanics.rank",
                        verbose_name="Ранг события",
                    ),
                ),
            ],
            options={
                "verbose_name": "Миссия",
                "verbose_name_plural": "Миссии",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_artifacts",
                        to="game_world.artifact",
                        verbose_name="Артефакт",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_artifacts",
                        to="game_world.event",
                        verbose_name="Событие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Артефакт события",
                "verbose_name_plural": "Артефакты событий",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="event",
            name="artifacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                through="game_world.EventArtifact",
                to="game_world.artifact",
                verbose_name="Артефакты",
            ),
        ),
        migrations.CreateModel(
            name="EventCompetency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                (
                    "experience",
                    models.IntegerField(
                        default=1, help_text="На сколько повысится уровень компетенции", verbose_name="Очки прокачки"
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_competencies",
                        to="game_mechanics.competency",
                        verbose_name="Компетенция",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_competencies",
                        to="game_world.event",
                        verbose_name="Миссия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компетенция миссии",
                "verbose_name_plural": "Компетенции миссий",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="event",
            name="competencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                through="game_world.EventCompetency",
                to="game_mechanics.competency",
                verbose_name="Компетенции",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="game_world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="game_world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="events", verbose_name="Иконка")),
                ("name", models.CharField(max_length=256, verbose_name="Название миссии")),
                ("description", models.TextField(verbose_name="Описание миссии")),
                ("experience", models.PositiveIntegerField(default=0, verbose_name="Награда в опыте")),
                ("currency", models.PositiveIntegerField(default=0, verbose_name="Награда в валюте")),
                ("order", models.IntegerField(default=1, verbose_name="Порядок в ветке")),
                (
                    "is_key_mission",
                    models.BooleanField(
                        default=False,
                        help_text="Обязательная миссия для получения ранга",
                        verbose_name="Ключевая миссия",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Время на выполнение в днях"),
                ),
                (
                    "game_world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="game_world.gameworld",
                        verbose_name="Игровой мир",
                    ),
                ),
                (
                    "required_missions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Миссии, которые нужно выполнить для доступа к этой миссии",
                        related_name="unlocks_missions",
                        to="game_world.mission",
                        verbose_name="Необходимые миссии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Миссия",
                "verbose_name_plural": "Миссии",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MissionArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_artifacts",
                        to="game_world.artifact",
                        verbose_name="Артефакт",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_artifacts",
                        to="game_world.mission",
                        verbose_name="Миссия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Артефакт миссии",
                "verbose_name_plural": "Артефакты миссий",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="mission",
            name="artifacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="missions",
                through="game_world.MissionArtifact",
                to="game_world.artifact",
                verbose_name="Награды-артефакты",
            ),
        ),
        migrations.CreateModel(
            name="MissionBranch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="mission_branches", verbose_name="Иконка")),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("color", models.CharField(max_length=256, verbose_name="Цвет")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                (
                    "start_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата и время для запуска"),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Время на выполнение в днях"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_branches",
                        to="game_world.activitycategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "game_world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_branches",
                        to="game_world.gameworld",
                        verbose_name="Игровой мир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ветка миссий",
                "verbose_name_plural": "Ветки миссий",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
