# Generated by Django 5.2.6 on 2025-09-24 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_mechanics", "0002_initial"),
        ("game_world", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="missionbranch",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_branches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ментор",
            ),
        ),
        migrations.AddField(
            model_name="missionbranch",
            name="rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mission_branches",
                to="game_mechanics.rank",
                verbose_name="Ранг ветки миссий",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="game_world.missionbranch",
                verbose_name="Ветка",
            ),
        ),
        migrations.AddField(
            model_name="missioncompetency",
            name="competency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_competencies",
                to="game_mechanics.competency",
                verbose_name="Компетенция",
            ),
        ),
        migrations.AddField(
            model_name="missioncompetency",
            name="mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_competencies",
                to="game_world.mission",
                verbose_name="Миссия",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="competencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="missions",
                through="game_world.MissionCompetency",
                to="game_mechanics.competency",
                verbose_name="Компетенции миссии",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="game_world.missionlevel",
                verbose_name="Уровень",
            ),
        ),
    ]
