# Generated by Django 5.2.6 on 2025-09-24 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_mechanics", "0002_initial"),
        ("game_world", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitycategory",
            options={
                "ordering": ("-id",),
                "verbose_name": "Категория активности",
                "verbose_name_plural": "Категории активностей",
            },
        ),
        migrations.AddField(
            model_name="artifact",
            name="color",
            field=models.CharField(blank=True, max_length=256, verbose_name="Цвет"),
        ),
        migrations.AddField(
            model_name="event",
            name="color",
            field=models.CharField(blank=True, max_length=256, verbose_name="Цвет"),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="modifier",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "Стандартный"),
                    ("EXPERIENCE_GAIN", "Прирост опыта"),
                    ("CURRENCY_GAIN", "Прирост валюты"),
                    ("STORE_DISCOUNT", "Скидка в магазине"),
                ],
                default="DEFAULT",
                max_length=20,
                verbose_name="Модификатор",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="required_number",
            field=models.PositiveIntegerField(
                help_text="Сколько пользователй должны посетить или закрыть это событие для общего успеха",
                verbose_name="Обязательное количество выполненных миссий для всех игроков",
            ),
        ),
        migrations.AlterField(
            model_name="eventcompetency",
            name="experience",
            field=models.PositiveIntegerField(
                default=1,
                help_text="На сколько повысится уровень компетенции за прохождение события",
                verbose_name="Очки прокачки",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_branches",
                to="game_world.activitycategory",
                verbose_name="Категория миссии",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                help_text="Ссылка на ментора, который может помочь в выполнении миссии.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_branches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ментор",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="rank",
            field=models.ForeignKey(
                help_text="Для какого ранга подходит эта ветка миссий",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mission_branches",
                to="game_mechanics.rank",
                verbose_name="Ранг ветки миссий",
            ),
        ),
        migrations.AlterField(
            model_name="missioncompetency",
            name="experience",
            field=models.PositiveIntegerField(
                default=1,
                help_text="На сколько повысится уровень компетенции за прохождение события",
                verbose_name="Очки прокачки",
            ),
        ),
    ]
