# Generated by Django 5.2.6 on 2025-09-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_world", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitycategory",
            name="color",
            field=models.CharField(blank=True, max_length=256, verbose_name="Цвет"),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="color",
            field=models.CharField(blank=True, max_length=256, verbose_name="Цвет"),
        ),
    ]
