# Generated by Django 5.2.6 on 2025-09-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("game_world", "0003_alter_activitycategory_options_artifact_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="color",
            field=models.CharField(blank=True, max_length=256, verbose_name="Цвет"),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно событие или нет"),
        ),
        migrations.AlterField(
            model_name="mission",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активная миссия или нет"),
        ),
        migrations.AlterField(
            model_name="mission",
            name="is_key_mission",
            field=models.BooleanField(
                default=False,
                help_text="Обязательная миссия для получения ранга",
                verbose_name="Ключевая миссия или нет",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активная ветка миссий или нет"),
        ),
        migrations.CreateModel(
            name="GameWorldStory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="history_game_worlds", verbose_name="Изображение"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                ("object_id", models.PositiveIntegerField(verbose_name="Id объекта")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип содержимого",
                    ),
                ),
                (
                    "game_world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_world_stories",
                        to="game_world.gameworld",
                        verbose_name="Игровой мир",
                    ),
                ),
            ],
            options={
                "verbose_name": "История игрового мира",
                "verbose_name_plural": "История игрового мира",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
