# Generated by Django 5.2.6 on 2025-09-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_world", "0003_alter_activitycategory_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_code_events", verbose_name="QR код"),
        ),
        migrations.AddField(
            model_name="mission",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="qr_code_missions",
                verbose_name="QR код",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="missions", verbose_name="Иконка"),
        ),
    ]
