# Generated by Django 5.2.6 on 2025-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_world", "0004_event_qr_code_mission_qr_code_alter_mission_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameworld",
            name="data_for_graph",
            field=models.JSONField(
                blank=True, help_text="Данные для графа", null=True, verbose_name="Данные для графа"
            ),
        ),
        migrations.DeleteModel(
            name="GameWorldSettings",
        ),
    ]
