# Generated by Django 5.2.6 on 2025-09-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_world", "0004_mission_color_alter_event_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitycategory",
            name="repeatability",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Через сколько дней повторять активность"
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="modifier",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "Стандартный"),
                    ("EXPERIENCE_GAIN", "Прирост опыта"),
                    ("CURRENCY_GAIN", "Прирост валюты"),
                    ("SHOP_DISCOUNT", "Скидка в магазине"),
                ],
                default="DEFAULT",
                max_length=20,
                verbose_name="Модификатор",
            ),
        ),
        migrations.AlterField(
            model_name="gameworld",
            name="name",
            field=models.CharField(max_length=256, unique=True, verbose_name="Название"),
        ),
    ]
