# Generated by Django 5.2.6 on 2025-10-01 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_mechanics", "0003_competency_level_alter_competency_name"),
        ("game_world", "0005_gameworld_data_for_graph_delete_gameworldsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="required_missions",
        ),
        migrations.AlterField(
            model_name="event",
            name="rank",
            field=models.ForeignKey(
                help_text="В рамках какого ранга это событие доступно для выполнения",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="game_mechanics.rank",
                verbose_name="Ранг события",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="branch",
            field=models.ForeignKey(
                help_text="Ветка миссии",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="game_world.missionbranch",
                verbose_name="Ветка",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="rank",
            field=models.ForeignKey(
                help_text="В рамках какого ранга эта ветка событий доступно для выполнения",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mission_branches",
                to="game_mechanics.rank",
                verbose_name="Ранг ветки миссий",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventartifact",
            constraint=models.UniqueConstraint(fields=("event", "artifact"), name="unique_event_and_artifact"),
        ),
        migrations.AddConstraint(
            model_name="eventcompetency",
            constraint=models.UniqueConstraint(fields=("event", "competency"), name="unique_event_and_competency"),
        ),
        migrations.AddConstraint(
            model_name="missionartifact",
            constraint=models.UniqueConstraint(fields=("mission", "artifact"), name="unique_mission_and_artifact"),
        ),
        migrations.AddConstraint(
            model_name="missioncompetency",
            constraint=models.UniqueConstraint(fields=("mission", "competency"), name="unique_mission_and_competency"),
        ),
    ]
