# Generated by Django 5.2.6 on 2025-09-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_world", "0005_activitycategory_repeatability_and_more"),
        ("user", "0002_remove_character_experience_remove_character_rank_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("-id",), "verbose_name": "Событие", "verbose_name_plural": "События"},
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                help_text="Ссылка на ментора, который может помочь в выполнении миссии.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_branches",
                to="user.character",
                verbose_name="Ментор",
            ),
        ),
    ]
