# Generated by Django 5.2.6 on 2025-09-27 06:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_world", "0006_alter_event_options_alter_missionbranch_mentor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitycategory",
            name="description",
            field=models.TextField(help_text="Описание категории активности", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="activitycategory",
            name="name",
            field=models.CharField(help_text="Название категории активности", max_length=256, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="activitycategory",
            name="repeatability",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Количество дней, через которую данную категории активности стоит повторить. Используется в некоторых миссиях и событиях. Например: категория 'Еженедельная миссия', repeatability = 7",
                null=True,
                verbose_name="Через сколько дней повторять активность",
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="description",
            field=models.TextField(blank=True, help_text="Описание артефакта", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="game_world",
            field=models.ForeignKey(
                help_text="Игровой мир в рамках которого создается артефакт",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="modifier",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "Стандартный"),
                    ("EXPERIENCE_GAIN", "Прирост опыта"),
                    ("CURRENCY_GAIN", "Прирост валюты"),
                    ("SHOP_DISCOUNT", "Скидка в магазине"),
                ],
                default="DEFAULT",
                help_text="Значение модификатора для артефакта. Только некоторые артефакты имеют модификатор",
                max_length=20,
                verbose_name="Модификатор",
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="modifier_value",
            field=models.PositiveIntegerField(
                help_text="Значение модификатора в %. На сколько увеличивается тот или иной показатель (обычно не больше 5 %).",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Значение модификатора в %",
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="name",
            field=models.CharField(
                help_text="Название артефакта", max_length=256, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(help_text="Описание события", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="event",
            name="game_world",
            field=models.ForeignKey(
                help_text="Игровой мир в рамках которого создается событие",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(help_text="Название события", max_length=256, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="gameworldstory",
            name="game_world",
            field=models.ForeignKey(
                help_text="Игровой мир в рамках которого создается история, особенности и описание его предметов и механик.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_world_stories",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="game_world",
            field=models.ForeignKey(
                help_text="Игровой мир в рамках которого создается миссия",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="game_world",
            field=models.ForeignKey(
                help_text="Игровой мир в рамках которого создается ветка миссий",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_branches",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
    ]
