# Generated by Django 5.2.6 on 2025-09-27 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("game_mechanics", "0004_alter_competency_description_and_more"),
        ("game_world", "0007_alter_activitycategory_description_and_more"),
        ("user", "0003_remove_user_role_character_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventcompetency",
            options={
                "ordering": ("-id",),
                "verbose_name": "Компетенция события",
                "verbose_name_plural": "Компетенции событий",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="artifacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Артефакты, которые может получить персонаж за успешное выполнение события",
                related_name="events",
                through="game_world.EventArtifact",
                to="game_world.artifact",
                verbose_name="Артефакты",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                help_text="Категория события",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="game_world.activitycategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="competencies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Компетенции, которые прокачиваются у персонажа за успешное выполнение события",
                related_name="events",
                through="game_world.EventCompetency",
                to="game_mechanics.competency",
                verbose_name="Компетенции",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="currency",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Награда в валюте, которую получит персонаж по завершению события",
                verbose_name="Награда в валюте",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                help_text="Описание события. Что должен сделать пользователей в рамках события с учетом трудовой деятельности",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="experience",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Награда в опыте, которое получит персонаж по завершению события",
                verbose_name="Награда в опыте",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Активно событие или нет", verbose_name="Активно событие или нет"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="rank",
            field=models.ForeignKey(
                help_text="В рамках какого ранга это событие доступно для выполнения",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="game_mechanics.rank",
                verbose_name="Ранг события",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="required_number",
            field=models.PositiveIntegerField(
                help_text="Сколько персонажей должны посетить или закрыть это событие для общего успеха",
                verbose_name="Обязательное количество выполненных событий для всех игроков",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время для запуска события. Используется для создания отложенных событий и должна сочетать с категорией.",
                null=True,
                verbose_name="Дата и время для запуска",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                help_text="Количество дней на успешное выполнение события",
                verbose_name="Количество дней на успешное выполнение события",
            ),
        ),
        migrations.AlterField(
            model_name="eventartifact",
            name="artifact",
            field=models.ForeignKey(
                help_text="Артефакт, который получает персонаж по успешному завершению события",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_artifacts",
                to="game_world.artifact",
                verbose_name="Артефакт",
            ),
        ),
        migrations.AlterField(
            model_name="eventartifact",
            name="event",
            field=models.ForeignKey(
                help_text="Событие персонажа за успешное выполнение которого он сможет получить артефакт",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_artifacts",
                to="game_world.event",
                verbose_name="Событие",
            ),
        ),
        migrations.AlterField(
            model_name="eventcompetency",
            name="competency",
            field=models.ForeignKey(
                help_text="Компетенция, которую прокачивает персонаж по успешному завершению события",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_competencies",
                to="game_mechanics.competency",
                verbose_name="Компетенция",
            ),
        ),
        migrations.AlterField(
            model_name="eventcompetency",
            name="event",
            field=models.ForeignKey(
                help_text="Событие персонажа за успешное выполнение которого он прокачивает компетенцию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_competencies",
                to="game_world.event",
                verbose_name="Событие",
            ),
        ),
        migrations.AlterField(
            model_name="eventcompetency",
            name="experience",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Сколько получит опыта компетенции за успешное прохождение события",
                verbose_name="Опыт",
            ),
        ),
        migrations.AlterField(
            model_name="gameworld",
            name="currency_name",
            field=models.CharField(help_text="Название валюты", verbose_name="Название валюты"),
        ),
        migrations.AlterField(
            model_name="gameworld",
            name="description",
            field=models.TextField(help_text="Описание игрового мира", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="gameworld",
            name="name",
            field=models.CharField(
                help_text="Название игрового мира", max_length=256, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="gameworld",
            name="standard_currency",
            field=models.PositiveIntegerField(
                help_text="Стандартный размер валюты, начисляемый за очень простую миссию",
                verbose_name="Стандартный размер валюты, начисляемый за очень простую миссию",
            ),
        ),
        migrations.AlterField(
            model_name="gameworld",
            name="standard_experience",
            field=models.PositiveIntegerField(
                help_text="Стандартный размер опыта, начисляемый за очень простую миссию",
                verbose_name="Стандартный размер опыта, начисляемый за очень простую миссию",
            ),
        ),
        migrations.AlterField(
            model_name="gameworldstory",
            name="content_type",
            field=models.ForeignKey(
                help_text="Тип содержимого",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Тип содержимого",
            ),
        ),
        migrations.AlterField(
            model_name="gameworldstory",
            name="game_world",
            field=models.ForeignKey(
                help_text="Игровой мир в рамках которого создается история, особенности и описание его предметов и механик",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_world_stories",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AlterField(
            model_name="gameworldstory",
            name="object_id",
            field=models.PositiveIntegerField(help_text="Id объекта", verbose_name="Id объекта"),
        ),
        migrations.AlterField(
            model_name="gameworldstory",
            name="text",
            field=models.TextField(help_text="Описание истории, лора", verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="mission",
            name="artifacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Артефакты, которые может получить персонаж за успешное выполнение миссии",
                related_name="missions",
                through="game_world.MissionArtifact",
                to="game_world.artifact",
                verbose_name="Артефакты",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="branch",
            field=models.ForeignKey(
                help_text="Ветка миссии в рамках которой",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="game_world.missionbranch",
                verbose_name="Ветка",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="competencies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Компетенции, которые прокачиваются у персонажа за успешное выполнение миссии",
                related_name="missions",
                through="game_world.MissionCompetency",
                to="game_mechanics.competency",
                verbose_name="Компетенции миссии",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="currency",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Награда в валюте, которую получит персонаж по завершению миссии",
                verbose_name="Награда в валюте",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="description",
            field=models.TextField(
                help_text="Описание миссии. Что должен сделать пользователей в рамках миссии с учетом трудовой деятельности",
                verbose_name="Описание миссии",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="experience",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Награда в опыте, которое получит персонаж по завершению миссии",
                verbose_name="Награда в опыте",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Активная миссия или нет", verbose_name="Активная миссия или нет"
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="is_key_mission",
            field=models.BooleanField(
                default=False,
                help_text="Является ли миссия обязательной чтобы получить новый ранг",
                verbose_name="Ключевая миссия или нет",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="name",
            field=models.CharField(help_text="Название миссии", max_length=256, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="mission",
            name="order",
            field=models.IntegerField(default=1, help_text="Порядок в ветке", verbose_name="Порядок в ветке"),
        ),
        migrations.AlterField(
            model_name="mission",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Количество дней на успешное выполнение миссии",
                null=True,
                verbose_name="Количество дней на успешное выполнение миссии",
            ),
        ),
        migrations.AlterField(
            model_name="missionartifact",
            name="artifact",
            field=models.ForeignKey(
                help_text="Артефакт, который получает персонаж по успешному завершению миссии",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_artifacts",
                to="game_world.artifact",
                verbose_name="Артефакт",
            ),
        ),
        migrations.AlterField(
            model_name="missionartifact",
            name="mission",
            field=models.ForeignKey(
                help_text="Миссия персонажа за успешное выполнение которого он сможет получить артефакт",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_artifacts",
                to="game_world.mission",
                verbose_name="Миссия",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="category",
            field=models.ForeignKey(
                help_text="Категория ветки миссии",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_branches",
                to="game_world.activitycategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание ветки миссий. Что должен сделать пользователей в рамках ветки миссий с учетом трудовой деятельности",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Активная ветка миссий или нет", verbose_name="Активная ветка миссий или нет"
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                help_text="Ментор, который может помочь в выполнении миссии",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_branches",
                to="user.character",
                verbose_name="Ментор",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="name",
            field=models.CharField(help_text="Название ветки миссий", max_length=256, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="rank",
            field=models.ForeignKey(
                help_text="В рамках какого ранга эта ветка событий доступно для выполнения",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mission_branches",
                to="game_mechanics.rank",
                verbose_name="Ранг ветки миссий",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время для запуска ветки событий. Используется для создания отложенных веток и должна сочетать с категорией.",
                null=True,
                verbose_name="Дата и время для запуска",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Количество дней на успешное выполнение ветки миссиий",
                null=True,
                verbose_name="Количество дней на успешное выполнение миссии",
            ),
        ),
        migrations.AlterField(
            model_name="missioncompetency",
            name="competency",
            field=models.ForeignKey(
                help_text="Компетенция, которую прокачивает персонаж по успешному завершению миссии",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_competencies",
                to="game_mechanics.competency",
                verbose_name="Компетенция",
            ),
        ),
        migrations.AlterField(
            model_name="missioncompetency",
            name="experience",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Сколько получит опыта компетенции за успешное прохождение миссии",
                verbose_name="Опыт",
            ),
        ),
        migrations.AlterField(
            model_name="missioncompetency",
            name="mission",
            field=models.ForeignKey(
                help_text="Миссия персонажа за успешное выполнение которого он прокачивает компетенцию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_competencies",
                to="game_world.mission",
                verbose_name="Миссия",
            ),
        ),
        migrations.AlterField(
            model_name="missionlevel",
            name="description",
            field=models.TextField(blank=True, help_text="Описание уровня миссии", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="missionlevel",
            name="multiplier_currency",
            field=models.PositiveIntegerField(
                help_text="Множитель валюты от стандартного, в %. На сколько процентов увеличивается стандартный размер валюты исходя из сложности миссии",
                verbose_name="Множитель валюты от стандартного, в %",
            ),
        ),
        migrations.AlterField(
            model_name="missionlevel",
            name="multiplier_experience",
            field=models.PositiveIntegerField(
                help_text="Множитель опыта от стандартного, в %. На сколько процентов увеличивается стандартный размер опыта исходя из сложности миссии",
                verbose_name="Множитель опыта от стандартного, в %",
            ),
        ),
        migrations.AlterField(
            model_name="missionlevel",
            name="name",
            field=models.CharField(help_text="Название уровня миссии", max_length=256, verbose_name="Название"),
        ),
    ]
