# Generated by Django 5.2.6 on 2025-09-27 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_world", "0008_alter_eventcompetency_options_alter_event_artifacts_and_more"),
        ("user", "0003_remove_user_role_character_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="category",
            field=models.ForeignKey(
                default=1,
                help_text="Категория ветки миссии",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="game_world.activitycategory",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mission",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                help_text="Ментор, который может помочь в выполнении миссии",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_mentors",
                to="user.character",
                verbose_name="Ментор",
            ),
        ),
        migrations.AlterField(
            model_name="missionbranch",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                help_text="Ментор, который может помочь в выполнении ветки миссий",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_branches",
                to="user.character",
                verbose_name="Ментор",
            ),
        ),
    ]
