# Generated by Django 5.2.6 on 2025-09-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="role",
            field=models.CharField(
                choices=[
                    ("CANDIDATE", "Кандидат"),
                    ("EMPLOYEE", "Сотрудник"),
                    ("MANAGER", "Менеджер"),
                    ("CONTENT_MANAGER", "Контент-менеджер"),
                    ("HR", "HR"),
                    ("ORGANIZER", "Организатор"),
                    ("ADMIN", "Администратор"),
                ],
                default="CANDIDATE",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
