# Generated by Django 5.2.6 on 2025-09-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_mechanics", "0002_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="character",
            name="rank",
        ),
        migrations.AddField(
            model_name="charactercompetency",
            name="is_received",
            field=models.BooleanField(default=False, verbose_name="Получена компетенция или нет"),
        ),
        migrations.AlterField(
            model_name="character",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный персонаж или нет"),
        ),
        migrations.AlterField(
            model_name="characterevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "В процессе"),
                    ("COMPLETED", "Выполнена"),
                    ("NEED_IMPROVEMENT", "Требует доработки"),
                    ("PENDING_REVIEW", "На проверке"),
                    ("FAILED", "Провалена"),
                ],
                default="IN_PROGRESS",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="charactermission",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "В процессе"),
                    ("COMPLETED", "Выполнена"),
                    ("NEED_IMPROVEMENT", "Требует доработки"),
                    ("PENDING_REVIEW", "На проверке"),
                    ("FAILED", "Провалена"),
                ],
                default="IN_PROGRESS",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="CharacterRank",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("experience", models.PositiveIntegerField(default=0, verbose_name="Опыт")),
                ("is_received", models.BooleanField(default=False, verbose_name="Получен ранг или нет")),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_ranks",
                        to="user.character",
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_ranks",
                        to="game_mechanics.rank",
                        verbose_name="Ранг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ранг персонажа",
                "verbose_name_plural": "Ранги персонажей",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="character",
            name="ranks",
            field=models.ManyToManyField(
                blank=True,
                related_name="characters",
                through="user.CharacterRank",
                to="game_mechanics.rank",
                verbose_name="Ранг",
            ),
        ),
    ]
