# Generated by Django 5.2.6 on 2025-09-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_world", "0006_alter_event_options_alter_missionbranch_mentor"),
        ("user", "0002_remove_character_experience_remove_character_rank_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="character",
            name="role",
            field=models.CharField(
                choices=[
                    ("CANDIDATE", "Кандидат"),
                    ("EMPLOYEE", "Сотрудник"),
                    ("MANAGER", "Менеджер"),
                    ("HR", "HR"),
                    ("ORGANIZER", "Организатор"),
                    ("ADMIN", "Администратор"),
                ],
                default="CANDIDATE",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                related_name="characters",
                through="user.CharacterEvent",
                through_fields=("character", "event"),
                to="game_world.event",
                verbose_name="События",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="missions",
            field=models.ManyToManyField(
                blank=True,
                related_name="characters",
                through="user.CharacterMission",
                through_fields=("character", "mission"),
                to="game_world.mission",
                verbose_name="Миссии",
            ),
        ),
        migrations.AlterField(
            model_name="characterevent",
            name="inspector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="character_event_inspectors",
                to="user.character",
                verbose_name="Проверяющий",
            ),
        ),
        migrations.AlterField(
            model_name="charactermission",
            name="inspector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="character_mission_inspectors",
                to="user.character",
                verbose_name="Проверяющий",
            ),
        ),
    ]
