# Generated by Django 5.2.6 on 2025-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_character_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterevent",
            name="final_status_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время проставления конечного статуса"
            ),
        ),
        migrations.AddField(
            model_name="charactermission",
            name="final_status_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время проставления конечного статуса"
            ),
        ),
        migrations.AlterField(
            model_name="characterevent",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Крайняя дата и время задачи, когда она должна быть выполнена"
            ),
        ),
        migrations.AlterField(
            model_name="characterevent",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время когда задача получена"),
        ),
    ]
