# Generated by Django 5.2.6 on 2025-09-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_characterevent_final_status_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermission",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Крайняя дата и время задачи, когда она должна быть выполнена",
            ),
        ),
        migrations.AlterField(
            model_name="charactermission",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время когда задача получена"),
        ),
    ]
