# Generated by Django 5.2.6 on 2025-09-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_charactermission_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterevent",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время, когда задача получена",
            ),
        ),
        migrations.AlterField(
            model_name="charactermission",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время, когда задача получена",
            ),
        ),
        migrations.AlterField(
            model_name="charactermissionbranch",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Крайняя дата и время задачи, когда она должна быть выполнена",
            ),
        ),
        migrations.AlterField(
            model_name="charactermissionbranch",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время, когда задача получена",
            ),
        ),
    ]
