# Generated by Django 5.2.6 on 2025-09-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_characterevent_start_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="experience",
            field=models.PositiveIntegerField(default=0, verbose_name="Опыт"),
        ),
        migrations.AlterField(
            model_name="characterevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "В процессе"),
                    ("COMPLETED", "Завершена"),
                    ("NEED_IMPROVEMENT", "Требует доработки"),
                    ("PENDING_REVIEW", "На проверке"),
                    ("FAILED", "Провалена"),
                ],
                default="IN_PROGRESS",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="charactermission",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "В процессе"),
                    ("COMPLETED", "Завершена"),
                    ("NEED_IMPROVEMENT", "Требует доработки"),
                    ("PENDING_REVIEW", "На проверке"),
                    ("FAILED", "Провалена"),
                ],
                default="IN_PROGRESS",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
