# Generated by Django 5.2.6 on 2025-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_character_experience_alter_characterevent_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactercompetency",
            name="received_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время получения"),
        ),
        migrations.AddField(
            model_name="characterrank",
            name="received_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время получения"),
        ),
    ]
