apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.production.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: celery-beat
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-beat
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.production.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: celery-beat
    spec:
      containers:
        - args:
            - poetry
            - run
            - celery
            - -A
            - alabuga.celery
            - beat
            - -l
            - info
          envFrom:
            - configMapRef:
                name: env
          image: ghcr.io/abat-voix/alabuga-oneplusplus-backend:latest
          name: celery-beat
      restartPolicy: Always
