# Generated by Django 5.2.6 on 2025-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("name", models.CharField(max_length=256, unique=True, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("required_experience", models.PositiveIntegerField(verbose_name="Требуемый опыт")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="competencies", verbose_name="Иконка")),
                ("color", models.CharField(blank=True, max_length=256, verbose_name="Цвет")),
            ],
            options={
                "verbose_name": "Компетенция",
                "verbose_name_plural": "Компетенции",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("name", models.CharField(max_length=256, unique=True, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("required_experience", models.PositiveIntegerField(verbose_name="Требуемый опыт")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="ranks", verbose_name="Иконка")),
                ("color", models.CharField(blank=True, max_length=256, verbose_name="Цвет")),
            ],
            options={
                "verbose_name": "Ранг",
                "verbose_name_plural": "Ранги",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RequiredRankCompetency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("required_experience", models.PositiveIntegerField(verbose_name="Требуемый опыт")),
            ],
            options={
                "verbose_name": "Требование к компетенции",
                "verbose_name_plural": "Требования к компетенциям",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
