# Generated by Django 5.2.6 on 2025-09-27 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Используется при генерации объектов через для понимания новый объект или старый",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название компетенции в рамках игрового мира",
                        max_length=256,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание компетенции в рамках игрового мира",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "required_experience",
                    models.PositiveIntegerField(
                        help_text="Количество опыта, которое необходимо получить чтобы полностью изучить компетенцию и получить новую компетенцию",
                        verbose_name="Требуемый опыт",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="competencies",
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=256, verbose_name="Цвет"),
                ),
            ],
            options={
                "verbose_name": "Компетенция",
                "verbose_name_plural": "Компетенции",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Используется при генерации объектов через для понимания новый объект или старый",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название ранга в рамках игрового мира",
                        max_length=256,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание ранга в рамках игрового мира",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "required_experience",
                    models.PositiveIntegerField(
                        help_text="Количество опыта, которое необходимо получить чтобы полностью закрыть ранг и получить новый ранг",
                        verbose_name="Требуемый опыт",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="ranks", verbose_name="Иконка"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=256, verbose_name="Цвет"),
                ),
            ],
            options={
                "verbose_name": "Ранг",
                "verbose_name_plural": "Ранги",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RequiredRankCompetency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Используется при генерации объектов через для понимания новый объект или старый",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Требование к компетенции",
                "verbose_name_plural": "Требования к компетенциям",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
