# Generated by Django 5.2.6 on 2025-09-23 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_mechanics", "0001_initial"),
        ("game_world", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competency",
            name="game_world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competencies",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AddField(
            model_name="rank",
            name="game_world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranks",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AddField(
            model_name="rank",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="game_mechanics.rank",
                verbose_name="Родительский ранг",
            ),
        ),
        migrations.AddField(
            model_name="requiredrankcompetency",
            name="competency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_rank_competencies",
                to="game_mechanics.competency",
                verbose_name="Компетенция",
            ),
        ),
        migrations.AddField(
            model_name="requiredrankcompetency",
            name="rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_rank_competencies",
                to="game_mechanics.rank",
                verbose_name="Ранг",
            ),
        ),
    ]
