# Generated by Django 5.2.6 on 2025-09-27 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_mechanics", "0001_initial"),
        ("game_world", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competency",
            name="game_world",
            field=models.ForeignKey(
                help_text="Игровой мир в рамках которого создается компетенция",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competencies",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AddField(
            model_name="competency",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Родительская компетенция. Используется для указания уровней компетенций. Ссылается на компетенцию уровня ниже",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="game_mechanics.competency",
                verbose_name="Родительская компетенция",
            ),
        ),
        migrations.AddField(
            model_name="rank",
            name="game_world",
            field=models.ForeignKey(
                help_text="Игровой мир в рамках которого создается ранг",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranks",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AddField(
            model_name="rank",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Родительский ранг. Используется для указания уровня ранга. Ссылается на ранг уровня ниже. Ранги имеют линейный вид.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="game_mechanics.rank",
                verbose_name="Родительский ранг",
            ),
        ),
        migrations.AddField(
            model_name="requiredrankcompetency",
            name="competency",
            field=models.ForeignKey(
                help_text="Компетенция, которую нужно обязательно получить, чтобы повысить ранг",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_rank_competencies",
                to="game_mechanics.competency",
                verbose_name="Компетенция",
            ),
        ),
        migrations.AddField(
            model_name="requiredrankcompetency",
            name="rank",
            field=models.ForeignKey(
                help_text="Ранг, в рамках которого нужно получить определенные компетенции",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_rank_competencies",
                to="game_mechanics.rank",
                verbose_name="Ранг",
            ),
        ),
    ]
