# Generated by Django 5.2.6 on 2025-09-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_mechanics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competency",
            name="level",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Уровень компетенции. Повышается на уровень родительской компетенции + 1",
                verbose_name="Уровень компетенции",
            ),
        ),
        migrations.AlterField(
            model_name="competency",
            name="name",
            field=models.CharField(
                help_text="Название компетенции в рамках игрового мира",
                max_length=256,
                verbose_name="Название",
            ),
        ),
    ]
