# Generated by Django 5.2.6 on 2025-09-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_mechanics", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requiredrankcompetency",
            name="required_experience",
        ),
    ]
