# Generated by Django 5.2.6 on 2025-09-27 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_mechanics", "0003_remove_requiredrankcompetency_required_experience"),
        ("game_world", "0007_alter_activitycategory_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competency",
            name="description",
            field=models.TextField(
                blank=True, help_text="Описание компетенции в рамках игрового мира", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="competency",
            name="game_world",
            field=models.ForeignKey(
                help_text="Игровой мир в рамках которого создается компетенция",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competencies",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AlterField(
            model_name="competency",
            name="name",
            field=models.CharField(
                help_text="Название компетенции в рамках игрового мира",
                max_length=256,
                unique=True,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="competency",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Родительская компетенция. Используется для указания уровней компетенций. Ссылается на компетенцию уровня ниже",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="game_mechanics.competency",
                verbose_name="Родительская компетенция",
            ),
        ),
        migrations.AlterField(
            model_name="competency",
            name="required_experience",
            field=models.PositiveIntegerField(
                help_text="Количество опыта, которое необходимо получить чтобы полностью изучить компетенцию и получить новую компетенцию",
                verbose_name="Требуемый опыт",
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="description",
            field=models.TextField(
                blank=True, help_text="Описание ранга в рамках игрового мира", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="game_world",
            field=models.ForeignKey(
                help_text="Игровой мир в рамках которого создается ранг",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranks",
                to="game_world.gameworld",
                verbose_name="Игровой мир",
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="name",
            field=models.CharField(
                help_text="Название ранга в рамках игрового мира", max_length=256, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Родительский ранг. Используется для указания уровня ранга. Ссылается на ранг уровня ниже. Ранги имеют линейный вид.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="game_mechanics.rank",
                verbose_name="Родительский ранг",
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="required_experience",
            field=models.PositiveIntegerField(
                help_text="Количество опыта, которое необходимо получить чтобы полностью закрыть ранг и получить новый ранг",
                verbose_name="Требуемый опыт",
            ),
        ),
        migrations.AlterField(
            model_name="requiredrankcompetency",
            name="competency",
            field=models.ForeignKey(
                help_text="Компетенция, которую нужно обязательно получить, чтобы повысить ранг",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_rank_competencies",
                to="game_mechanics.competency",
                verbose_name="Компетенция",
            ),
        ),
        migrations.AlterField(
            model_name="requiredrankcompetency",
            name="rank",
            field=models.ForeignKey(
                help_text="Ранг, в рамках которого нужно получить определенные компетенции",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_rank_competencies",
                to="game_mechanics.rank",
                verbose_name="Ранг",
            ),
        ),
    ]
