# Generated by Django 4.2.24 on 2025-09-19 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('MERCH', 'Мерч'), ('TICKET', 'Билет'), ('BONUS', 'Бонус'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Категория')),
                ('price', models.IntegerField(default=0, verbose_name='Цена в мане')),
                ('quantity', models.IntegerField(default=0, help_text='Доступное количество товара. 0 - бесконечное количество', verbose_name='Количество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_items', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category', 'price'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('price', models.IntegerField(help_text='Цена на момент покупки', verbose_name='Цена покупки')),
                ('status', models.CharField(choices=[('PENDING', 'В обработке'), ('CONFIRMED', 'Подтверждена'), ('DELIVERED', 'Доставлена'), ('CANCELLED', 'Отменена')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('delivery_info', models.TextField(blank=True, verbose_name='Информация о доставке')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='shop.shopitem', verbose_name='Товар')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
