# Generated by Django 5.2.6 on 2025-09-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_mechanics", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopItemCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("name", models.CharField(max_length=256, unique=True, verbose_name="Название категории")),
                ("description", models.TextField(verbose_name="Описание категории")),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="shop_item_categories", verbose_name="Иконка"),
                ),
                ("color", models.CharField(blank=True, max_length=256, verbose_name="Цвет")),
                (
                    "purchase_restriction",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ограничение на покупку, количество"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория товара в магазине",
                "verbose_name_plural": "Категории товаров в магазине",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserPurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("price", models.PositiveIntegerField(verbose_name="Цена на момент покупки в валюте")),
                ("number", models.PositiveIntegerField(verbose_name="Количество")),
                ("total_sum", models.PositiveIntegerField(verbose_name="Общая сумма")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "В обработке"),
                            ("CONFIRMED", "Подтверждена"),
                            ("DELIVERED", "Доставлена"),
                            ("CANCELLED", "Отменена"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("additional_info", models.TextField(blank=True, verbose_name="Дополнительная информация")),
            ],
            options={
                "verbose_name": "Покупка пользователя",
                "verbose_name_plural": "Покупки пользователей",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("price", models.PositiveIntegerField(verbose_name="Цена в валюте")),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Доступное количество товара. 0 - бесконечное количество", verbose_name="Количество"
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="shop_items", verbose_name="Изображение")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "start_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата и время старта продаж"),
                ),
                (
                    "time_to_buy",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Время на покупку, в днях"),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_items",
                        to="game_mechanics.competency",
                        verbose_name="Компетенция",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Заполняется только при наличии rank и/или competency",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="shop.shopitem",
                        verbose_name="Родительский товар",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_items",
                        to="game_mechanics.rank",
                        verbose_name="Ранг",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_items",
                        to="shop.shopitemcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
