# Generated by Django 5.2.6 on 2025-10-02 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CharacterPurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("uuid", models.UUIDField(default=uuid.uuid4, help_text="UUID", unique=True, verbose_name="UUID")),
                ("price", models.PositiveIntegerField(verbose_name="Цена на момент покупки в валюте")),
                ("number", models.PositiveIntegerField(verbose_name="Количество")),
                ("discount", models.PositiveIntegerField(default=0, verbose_name="Скидка")),
                ("total_sum", models.PositiveIntegerField(verbose_name="Общая сумма")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "В обработке"),
                            ("CONFIRMED", "Подтверждена"),
                            ("SENT", "Отправлена"),
                            ("DELIVERED", "Доставлена"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("additional_info", models.TextField(blank=True, verbose_name="Дополнительная информация")),
            ],
            options={
                "verbose_name": "Покупка пользователя",
                "verbose_name_plural": "Покупки пользователей",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("uuid", models.UUIDField(default=uuid.uuid4, help_text="UUID", unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("price", models.PositiveIntegerField(verbose_name="Цена в валюте")),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Доступное количество товара. 0 - бесконечное количество", verbose_name="Количество"
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="shop_items", verbose_name="Изображение")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активный товар в магазине или нет")),
                (
                    "start_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата и время старта продаж"),
                ),
                (
                    "time_to_buy",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Время на покупку, в днях"),
                ),
                (
                    "purchase_restriction",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ограничение на покупку, количество"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopItemCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания объекта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время изменения объекта")),
                ("uuid", models.UUIDField(default=uuid.uuid4, help_text="UUID", unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=256, unique=True, verbose_name="Название категории")),
                ("description", models.TextField(verbose_name="Описание категории")),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="shop_item_categories", verbose_name="Иконка"),
                ),
                ("color", models.CharField(blank=True, max_length=256, verbose_name="Цвет")),
                (
                    "purchase_restriction",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ограничение на покупку, количество"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория товара в магазине",
                "verbose_name_plural": "Категории товаров в магазине",
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
