# Generated by Django 5.2.6 on 2025-10-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_mechanics", "0002_initial"),
        ("shop", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterpurchase",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_purchases",
                to="user.character",
                verbose_name="Покупатель",
            ),
        ),
        migrations.AddField(
            model_name="characterpurchase",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager_purchases",
                to="user.character",
                verbose_name="Менеджер",
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="competency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_items",
                to="game_mechanics.competency",
                verbose_name="Компетенция",
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Заполняется только при наличии rank и/или competency",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="shop.shopitem",
                verbose_name="Родительский товар",
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_items",
                to="game_mechanics.rank",
                verbose_name="Ранг",
            ),
        ),
        migrations.AddField(
            model_name="characterpurchase",
            name="shop_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="shop.shopitem",
                verbose_name="Товар",
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_items",
                to="shop.shopitemcategory",
                verbose_name="Категория",
            ),
        ),
    ]
