# Generated by Django 5.2.6 on 2025-09-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_initial"),
        ("user", "0007_charactercompetency_received_datetime_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserPurchase",
            new_name="CharacterPurchase",
        ),
    ]
