# Generated by Django 5.2.6 on 2025-09-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopitem",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный товар в магазине или нет"),
        ),
    ]
