# Generated by Django 5.2.6 on 2025-09-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_userpurchase_characterpurchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterpurchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "В обработке"),
                    ("CONFIRMED", "Подтверждена"),
                    ("SENT", "Отправлена"),
                    ("DELIVERED", "Доставлена"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
