# Generated by Django 5.2.6 on 2025-09-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_shopitem_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpurchase",
            name="discount",
            field=models.PositiveIntegerField(default=0, verbose_name="Скидка"),
        ),
    ]
