# Generated by Django 5.2.6 on 2025-09-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_userpurchase_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopitem",
            name="purchase_restriction",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Ограничение на покупку, количество"),
        ),
    ]
