# Generated by Django 5.2.6 on 2025-09-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_shopitem_purchase_restriction"),
        ("user", "0003_remove_user_role_character_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpurchase",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_purchases",
                to="user.character",
                verbose_name="Покупатель",
            ),
        ),
        migrations.AlterField(
            model_name="userpurchase",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager_purchases",
                to="user.character",
                verbose_name="Менеджер",
            ),
        ),
    ]
